### ISSUE TITLE
Convert repo to GitHub template repository

### ISSUE THREAD

**Issue by ajit283** [coglabuzh/jspsych-template#1]
This might be a good use case for the template repository feature:
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

It would make it very easy for users to create an experiment on the basis of this repository.

**Comment by chenyu-psy** [comment]
Thank you for your suggestion. It could be a personal preference of mine to always include multiple experiments in one repository as a project. Using this repository as a template repository does not work for me. But I will discuss with other people and see if they need this feature.
